## 2-11. 프로젝트 (1) load_digits : 손글씨를 분류해 봅시다


#### (1) 필요한 모듈 import하기


In [1]:
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

#### (2) 데이터 준비


In [2]:
digits = load_digits()
digits

{'data': array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ..., 10.,  0.,  0.],
        [ 0.,  0.,  0., ..., 16.,  9.,  0.],
        ...,
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  2., ..., 12.,  0.,  0.],
        [ 0.,  0., 10., ..., 12.,  1.,  0.]]),
 'target': array([0, 1, 2, ..., 8, 9, 8]),
 'frame': None,
 'feature_names': ['pixel_0_0',
  'pixel_0_1',
  'pixel_0_2',
  'pixel_0_3',
  'pixel_0_4',
  'pixel_0_5',
  'pixel_0_6',
  'pixel_0_7',
  'pixel_1_0',
  'pixel_1_1',
  'pixel_1_2',
  'pixel_1_3',
  'pixel_1_4',
  'pixel_1_5',
  'pixel_1_6',
  'pixel_1_7',
  'pixel_2_0',
  'pixel_2_1',
  'pixel_2_2',
  'pixel_2_3',
  'pixel_2_4',
  'pixel_2_5',
  'pixel_2_6',
  'pixel_2_7',
  'pixel_3_0',
  'pixel_3_1',
  'pixel_3_2',
  'pixel_3_3',
  'pixel_3_4',
  'pixel_3_5',
  'pixel_3_6',
  'pixel_3_7',
  'pixel_4_0',
  'pixel_4_1',
  'pixel_4_2',
  'pixel_4_3',
  'pixel_4_4',
  'pixel_4_5',
  'pixel_4_6',
  'pixel_4_7',
  'pixel_5_0',
  'pixel_5_1',
 

In [3]:
dir(digits)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

#### (3) 데이터 이해하기
- Feature Data 지정하기
- Label Data 지정하기
- Target Names 출력해 보기
- 데이터 Describe 해 보기

In [14]:
# 데이터만 따로 저장
digits_data = digits.data
digits_data

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [15]:
# 데이터 shape 확인
digits_data.shape

(1797, 64)

In [16]:
# 데이터 feature 이름 확인
digits.feature_names

['pixel_0_0',
 'pixel_0_1',
 'pixel_0_2',
 'pixel_0_3',
 'pixel_0_4',
 'pixel_0_5',
 'pixel_0_6',
 'pixel_0_7',
 'pixel_1_0',
 'pixel_1_1',
 'pixel_1_2',
 'pixel_1_3',
 'pixel_1_4',
 'pixel_1_5',
 'pixel_1_6',
 'pixel_1_7',
 'pixel_2_0',
 'pixel_2_1',
 'pixel_2_2',
 'pixel_2_3',
 'pixel_2_4',
 'pixel_2_5',
 'pixel_2_6',
 'pixel_2_7',
 'pixel_3_0',
 'pixel_3_1',
 'pixel_3_2',
 'pixel_3_3',
 'pixel_3_4',
 'pixel_3_5',
 'pixel_3_6',
 'pixel_3_7',
 'pixel_4_0',
 'pixel_4_1',
 'pixel_4_2',
 'pixel_4_3',
 'pixel_4_4',
 'pixel_4_5',
 'pixel_4_6',
 'pixel_4_7',
 'pixel_5_0',
 'pixel_5_1',
 'pixel_5_2',
 'pixel_5_3',
 'pixel_5_4',
 'pixel_5_5',
 'pixel_5_6',
 'pixel_5_7',
 'pixel_6_0',
 'pixel_6_1',
 'pixel_6_2',
 'pixel_6_3',
 'pixel_6_4',
 'pixel_6_5',
 'pixel_6_6',
 'pixel_6_7',
 'pixel_7_0',
 'pixel_7_1',
 'pixel_7_2',
 'pixel_7_3',
 'pixel_7_4',
 'pixel_7_5',
 'pixel_7_6',
 'pixel_7_7']

In [18]:
# 라벨의 텍스트적 라벨 확인
digits.target_names

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
# 라벨 따로 할당
digits_label = digits.target

# 라벨 shape 확인
print(digits_label.shape)

(1797,)


In [24]:
# 데이터를 보면
# 1) 0~9까지의 숫자를 담은 이미지 데이터이고
# 2) 이 이미지들의 실제 값은 target에 1차원 벡터로 저장되어 있다.
# 3) 데이터 개수는 1791개, 이들의 feature는 64개이다.
# 4) 그러나 feature 64개는 8*8 이미지를 flatten하게 놓은 것으로서 다른 의미는 없다.

#### (4) train, test 데이터 분리


In [26]:
# 데이터셋 분리
X_train, X_test, y_train, y_test = train_test_split(digits_data,
                                                   digits_label,
                                                   test_size=0.2,
                                                   random_state=13)

print(f"X_train 개수는 {len(X_train)}")
print(f"y_train 개수는 {len(y_train)}")
print(f"X_test 개수는 {len(X_test)}")
print(f"y_test 개수는 {len(y_test)}")

X_train 개수는 1437
y_train 개수는 1437
X_test 개수는 360
y_test 개수는 360


#### (5) 다양한 모델로 학습시켜보기


In [47]:
# Decision Tree 사용
from sklearn.tree import DecisionTreeClassifier

dt_model = DecisionTreeClassifier()
print(dt_model._estimator_type)

# 학습
dt_model.fit(X_train, y_train)

# 예측
dt_y_pred = dt_model.predict(X_test)
dt_y_pred

classifier


array([9, 1, 4, 3, 3, 1, 4, 9, 5, 8, 8, 0, 2, 5, 0, 4, 4, 6, 4, 1, 1, 9,
       6, 4, 4, 9, 5, 4, 3, 1, 5, 0, 9, 5, 1, 0, 0, 1, 8, 0, 1, 8, 2, 1,
       0, 1, 9, 9, 4, 4, 3, 6, 1, 8, 0, 1, 6, 5, 5, 2, 5, 9, 1, 1, 3, 5,
       3, 3, 7, 6, 5, 6, 3, 1, 7, 6, 4, 1, 6, 8, 5, 5, 9, 6, 2, 5, 0, 8,
       9, 6, 1, 3, 0, 7, 7, 5, 5, 8, 6, 8, 4, 7, 2, 5, 6, 3, 7, 5, 8, 5,
       5, 4, 9, 3, 3, 2, 7, 8, 9, 8, 6, 7, 7, 7, 5, 3, 1, 2, 8, 3, 5, 9,
       9, 5, 2, 7, 6, 8, 0, 3, 6, 0, 5, 3, 9, 3, 7, 5, 6, 3, 6, 3, 2, 9,
       1, 0, 6, 7, 2, 3, 0, 0, 4, 9, 5, 4, 9, 3, 4, 1, 5, 9, 7, 0, 2, 3,
       8, 4, 7, 2, 5, 5, 4, 8, 2, 2, 0, 4, 8, 4, 0, 5, 3, 2, 9, 1, 8, 8,
       1, 4, 5, 6, 5, 0, 1, 3, 6, 5, 2, 3, 4, 7, 0, 6, 0, 8, 7, 2, 9, 6,
       2, 7, 3, 3, 9, 9, 5, 6, 6, 1, 6, 8, 6, 1, 2, 8, 3, 5, 2, 4, 0, 0,
       7, 2, 9, 8, 6, 1, 6, 9, 5, 0, 1, 6, 3, 2, 3, 9, 5, 3, 1, 2, 6, 9,
       4, 4, 8, 3, 3, 4, 1, 2, 6, 8, 9, 1, 4, 9, 4, 6, 1, 1, 2, 9, 2, 0,
       8, 0, 3, 5, 5, 5, 2, 9, 2, 5, 9, 2, 7, 0, 6,

In [48]:
# Random Forest 사용
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier()
print(rf_model._estimator_type)

# 학습
rf_model.fit(X_train, y_train)

# 예측
rf_y_pred = rf_model.predict(X_test)
rf_y_pred

classifier


array([9, 1, 1, 3, 1, 3, 4, 9, 5, 8, 8, 0, 2, 5, 0, 4, 4, 6, 4, 1, 1, 1,
       6, 4, 4, 9, 5, 4, 3, 1, 5, 0, 9, 5, 1, 0, 0, 3, 8, 0, 1, 8, 2, 1,
       0, 1, 9, 9, 4, 4, 3, 6, 7, 8, 0, 1, 6, 5, 5, 2, 5, 9, 1, 1, 3, 5,
       3, 9, 7, 6, 5, 2, 3, 1, 7, 6, 1, 1, 6, 8, 5, 9, 9, 6, 2, 5, 0, 8,
       9, 6, 1, 3, 0, 7, 7, 5, 5, 8, 6, 2, 4, 7, 2, 5, 6, 3, 7, 5, 3, 5,
       5, 4, 9, 3, 3, 2, 7, 8, 9, 7, 2, 4, 7, 4, 5, 3, 2, 2, 8, 3, 5, 9,
       9, 5, 2, 7, 6, 8, 9, 3, 6, 0, 5, 3, 9, 3, 7, 5, 6, 2, 4, 3, 2, 9,
       4, 0, 6, 7, 2, 3, 0, 0, 4, 9, 5, 4, 1, 9, 4, 1, 5, 5, 7, 0, 2, 3,
       8, 4, 7, 2, 5, 5, 4, 8, 2, 2, 0, 4, 8, 4, 0, 5, 3, 2, 9, 6, 8, 8,
       1, 4, 5, 6, 5, 0, 1, 3, 6, 5, 2, 8, 0, 7, 0, 6, 0, 8, 7, 2, 8, 6,
       2, 7, 3, 3, 9, 9, 5, 6, 6, 9, 6, 0, 6, 4, 2, 7, 3, 5, 2, 4, 0, 0,
       7, 2, 3, 8, 6, 1, 6, 9, 5, 0, 1, 6, 3, 2, 3, 9, 5, 4, 1, 1, 6, 9,
       4, 4, 8, 3, 3, 4, 1, 2, 6, 6, 9, 1, 4, 9, 4, 6, 1, 1, 2, 9, 2, 0,
       8, 0, 1, 5, 5, 5, 2, 9, 8, 5, 9, 2, 7, 0, 6,

In [49]:
# SVM 사용
from sklearn import svm

svm_model = svm.SVC()
print(svm_model._estimator_type)

# 학습
svm_model.fit(X_train, y_train)

# 예측
svm_y_pred = svm_model.predict(X_test)
svm_y_pred

classifier


array([9, 1, 1, 3, 1, 3, 4, 9, 5, 8, 8, 0, 2, 5, 0, 4, 4, 6, 4, 1, 1, 1,
       6, 4, 4, 9, 5, 4, 3, 1, 5, 0, 1, 5, 1, 0, 0, 3, 8, 0, 1, 8, 2, 1,
       0, 1, 9, 9, 4, 4, 3, 6, 7, 8, 0, 1, 6, 5, 5, 2, 5, 9, 1, 1, 3, 5,
       3, 9, 7, 6, 5, 2, 3, 1, 7, 6, 1, 1, 6, 8, 5, 9, 9, 6, 2, 5, 0, 8,
       9, 6, 1, 3, 0, 7, 7, 5, 5, 8, 6, 2, 4, 7, 2, 5, 6, 3, 7, 5, 3, 5,
       5, 4, 9, 3, 3, 2, 7, 8, 9, 8, 2, 4, 7, 4, 5, 3, 2, 2, 8, 3, 5, 9,
       9, 5, 2, 7, 6, 8, 9, 3, 6, 0, 5, 3, 9, 3, 7, 5, 6, 2, 4, 3, 2, 9,
       4, 0, 6, 7, 2, 3, 0, 0, 4, 9, 5, 4, 1, 9, 4, 1, 5, 5, 7, 0, 2, 3,
       8, 4, 7, 2, 5, 5, 4, 8, 2, 2, 0, 4, 8, 4, 0, 5, 3, 2, 9, 6, 8, 8,
       1, 4, 5, 6, 5, 0, 1, 3, 6, 5, 2, 8, 0, 7, 0, 6, 0, 8, 7, 2, 2, 6,
       2, 7, 3, 3, 9, 9, 5, 6, 6, 9, 6, 0, 6, 4, 2, 7, 3, 5, 2, 4, 0, 0,
       7, 2, 3, 8, 6, 1, 6, 9, 5, 0, 1, 6, 3, 2, 3, 9, 5, 8, 1, 1, 6, 9,
       4, 4, 8, 3, 3, 4, 1, 2, 6, 6, 9, 1, 4, 9, 4, 6, 1, 1, 2, 9, 2, 0,
       8, 0, 1, 5, 5, 5, 2, 9, 8, 5, 9, 2, 7, 0, 6,

In [50]:
# SGDClassifier 사용
from sklearn.linear_model import SGDClassifier

SGDC_model = SGDClassifier()
print(SGDC_model._estimator_type)

# 학습
SGDC_model.fit(X_train, y_train)

# 예측
SGDC_y_pred = SGDC_model.predict(X_test)
SGDC_y_pred

classifier


array([9, 1, 4, 3, 1, 3, 4, 9, 5, 8, 8, 0, 2, 5, 0, 4, 4, 6, 4, 1, 1, 1,
       6, 4, 4, 9, 5, 4, 5, 1, 5, 0, 9, 5, 1, 0, 0, 7, 8, 0, 1, 8, 2, 1,
       0, 1, 9, 9, 4, 4, 3, 6, 7, 8, 0, 1, 6, 5, 5, 2, 5, 9, 1, 1, 3, 5,
       3, 9, 7, 6, 5, 2, 3, 1, 7, 6, 1, 1, 6, 8, 5, 9, 9, 6, 2, 5, 0, 8,
       9, 6, 1, 3, 0, 7, 7, 5, 5, 8, 6, 2, 4, 7, 2, 5, 6, 3, 7, 5, 3, 5,
       5, 4, 9, 3, 3, 2, 7, 1, 9, 7, 2, 4, 7, 4, 5, 3, 2, 2, 1, 3, 5, 9,
       9, 5, 2, 7, 6, 8, 9, 3, 6, 0, 5, 5, 9, 3, 7, 5, 6, 2, 4, 8, 2, 9,
       4, 0, 6, 7, 2, 3, 0, 0, 4, 9, 5, 4, 1, 9, 4, 1, 5, 5, 7, 0, 2, 9,
       8, 4, 7, 2, 5, 5, 4, 8, 2, 2, 0, 4, 8, 4, 0, 5, 3, 2, 9, 6, 8, 8,
       1, 4, 5, 6, 5, 0, 1, 3, 6, 5, 2, 8, 0, 7, 0, 6, 0, 8, 7, 2, 8, 6,
       2, 7, 3, 3, 9, 9, 5, 6, 6, 9, 6, 0, 6, 4, 2, 7, 3, 1, 2, 4, 0, 0,
       7, 2, 3, 8, 6, 1, 6, 9, 5, 0, 1, 6, 3, 2, 3, 9, 5, 4, 1, 1, 6, 9,
       4, 4, 8, 3, 3, 4, 1, 2, 6, 6, 9, 1, 4, 9, 4, 6, 1, 1, 2, 9, 2, 0,
       8, 0, 1, 5, 5, 5, 2, 9, 8, 5, 9, 2, 7, 0, 6,

In [51]:
# Logistic Regression 사용
from sklearn.linear_model import LogisticRegression

lr_model = LogisticRegression()
print(lr_model._estimator_type)

# 학습
lr_model.fit(X_train, y_train)

# 예측
lr_y_pred = lr_model.predict(X_test)
lr_y_pred

classifier


/opt/conda/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


array([9, 1, 4, 3, 7, 3, 4, 9, 5, 8, 8, 0, 2, 5, 0, 4, 4, 6, 4, 1, 1, 1,
       6, 4, 4, 9, 5, 4, 9, 1, 5, 0, 9, 5, 1, 0, 0, 3, 8, 0, 1, 8, 2, 1,
       0, 1, 9, 9, 4, 4, 3, 6, 7, 8, 0, 1, 6, 5, 5, 2, 5, 9, 1, 1, 3, 5,
       3, 9, 7, 6, 5, 2, 3, 1, 7, 6, 1, 1, 6, 9, 5, 9, 9, 6, 2, 3, 0, 8,
       9, 6, 1, 3, 0, 9, 7, 5, 5, 8, 6, 2, 4, 7, 2, 5, 6, 3, 7, 5, 3, 5,
       5, 4, 9, 3, 3, 2, 7, 8, 9, 8, 2, 4, 7, 4, 5, 3, 2, 2, 1, 3, 5, 9,
       9, 5, 2, 7, 6, 8, 9, 3, 6, 0, 5, 3, 9, 3, 7, 5, 6, 2, 4, 3, 2, 9,
       4, 0, 6, 7, 2, 3, 0, 0, 4, 9, 5, 4, 1, 9, 4, 9, 5, 5, 7, 0, 2, 9,
       8, 4, 7, 2, 5, 5, 4, 8, 2, 1, 0, 4, 8, 4, 0, 5, 3, 2, 9, 6, 8, 8,
       1, 4, 5, 6, 5, 0, 1, 3, 6, 5, 2, 8, 0, 7, 0, 6, 0, 8, 7, 2, 8, 6,
       1, 7, 3, 3, 9, 9, 5, 6, 6, 5, 6, 0, 6, 4, 2, 7, 3, 5, 2, 4, 0, 0,
       7, 2, 3, 8, 6, 1, 6, 9, 5, 0, 1, 6, 3, 2, 3, 9, 5, 4, 1, 1, 6, 9,
       4, 4, 8, 3, 3, 4, 1, 2, 6, 1, 9, 1, 4, 9, 4, 6, 1, 1, 2, 9, 2, 0,
       8, 0, 1, 5, 5, 5, 2, 9, 8, 5, 9, 2, 7, 0, 6,

#### (6) 모델을 평가해 보기
- 평가지표 선택 및 이유 설명

In [41]:
# 우선 데이터 불균형을 파악하기 위해 y_train, y_test 값을 봐보자면

import numpy as np
print('y_train')
print(np.unique(y_train, return_counts=True))
print("=======================")
print('y_test')
print(np.unique(y_test, return_counts=True))

# 골고루 섞여있음

y_train
(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([148, 145, 139, 146, 143, 137, 139, 153, 140, 147]))
y_test
(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([30, 37, 38, 37, 38, 45, 42, 26, 34, 33]))


#### 결론
- 선택한 평가지표 : accuracy
- 이유 : 데이터가 골고루 되어 있기에 데이터 전체 갯수에 대한 예측률을 알려주는 accuracy도 모델의 성능을 잘 보여줄 수 있다고 생각

In [55]:
# 모델별 평가하기
from sklearn.metrics import accuracy_score

print("Decision Tree")
print('Accuracy :', accuracy_score(y_test, dt_y_pred))
print("==================================================")
print("Random Forest")
print('Accuracy :', accuracy_score(y_test, rf_y_pred))
print("==================================================")
print("SVM")
print('Accuracy :', accuracy_score(y_test, svm_y_pred))
print("==================================================")
print("SGD Classifier")
print('Accuracy :', accuracy_score(y_test, SGDC_y_pred))
print("==================================================")
print("Logistic Regression")
print('Accuracy :', accuracy_score(y_test, lr_y_pred))
print("==================================================")

Decision Tree
Accuracy : 0.8722222222222222
Random Forest
Accuracy : 0.9777777777777777
SVM
Accuracy : 0.9833333333333333
SGD Classifier
Accuracy : 0.9527777777777777
Logistic Regression
Accuracy : 0.9472222222222222


## 2-12. 프로젝트 (2) load_wine : 와인을 분류해 봅시다


#### (1) 필요한 모듈 import하기


In [56]:
from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report


#### (2) 데이터 준비


In [57]:
wine = load_wine()
wine

{'data': array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
         1.065e+03],
        [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
         1.050e+03],
        [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
         1.185e+03],
        ...,
        [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
         8.350e+02],
        [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
         8.400e+02],
        [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
         5.600e+02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1

#### (3) 데이터 이해하기


In [58]:
wine.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names'])

In [59]:
print(wine.DESCR)

.. _wine_dataset:

Wine recognition dataset
------------------------

**Data Set Characteristics:**

    :Number of Instances: 178 (50 in each of three classes)
    :Number of Attributes: 13 numeric, predictive attributes and the class
    :Attribute Information:
 		- Alcohol
 		- Malic acid
 		- Ash
		- Alcalinity of ash  
 		- Magnesium
		- Total phenols
 		- Flavanoids
 		- Nonflavanoid phenols
 		- Proanthocyanins
		- Color intensity
 		- Hue
 		- OD280/OD315 of diluted wines
 		- Proline

    - class:
            - class_0
            - class_1
            - class_2
		
    :Summary Statistics:
    
    ============================= ==== ===== ======= =====
                                   Min   Max   Mean     SD
    ============================= ==== ===== ======= =====
    Alcohol:                      11.0  14.8    13.0   0.8
    Malic Acid:                   0.74  5.80    2.34  1.12
    Ash:                          1.36  3.23    2.36  0.27
    Alcalinity of Ash:            1

In [60]:
# 데이터만 따로 저장
wine_data = wine.data

# 라벨만 따로 저장
wine_label = wine.target

In [62]:
wine.target_names

array(['class_0', 'class_1', 'class_2'], dtype='<U7')

In [63]:
wine.feature_names

['alcohol',
 'malic_acid',
 'ash',
 'alcalinity_of_ash',
 'magnesium',
 'total_phenols',
 'flavanoids',
 'nonflavanoid_phenols',
 'proanthocyanins',
 'color_intensity',
 'hue',
 'od280/od315_of_diluted_wines',
 'proline']

In [92]:
# 데이터를 보면
# 1) wine 품종 3가지에 대한 데이터이고
# 2) 이 데이터들의 실제 값은 target에 1차원 벡터로 저장되어 있다.
# 3) 데이터 개수는 178개, 이들의 feature는 13개이다.
# 4) feature는 모두 numeric이다.


#### (4) train, test 데이터 분리


In [65]:
# 데이터셋 분리
X_train, X_test, y_train, y_test = train_test_split(wine_data,
                                                   wine_label,
                                                   test_size=0.2,
                                                   random_state=13)

print(f"X_train 개수는 {len(X_train)}")
print(f"y_train 개수는 {len(y_train)}")
print(f"X_test 개수는 {len(X_test)}")
print(f"y_test 개수는 {len(y_test)}")

X_train 개수는 142
y_train 개수는 142
X_test 개수는 36
y_test 개수는 36


#### (5) 다양한 모델로 학습시켜보기


In [67]:
# Decision Tree 사용
from sklearn.tree import DecisionTreeClassifier
dt_model = DecisionTreeClassifier()
print(dt_model._estimator_type)

# 학습
dt_model.fit(X_train, y_train)

# 예측
dt_y_pred = dt_model.predict(X_test)
dt_y_pred

classifier


array([1, 0, 2, 1, 1, 1, 2, 0, 1, 1, 0, 0, 2, 1, 2, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 2, 1, 1, 1, 0, 2, 1, 1, 0, 1, 0, 0])

In [68]:
# Random Forest 사용
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier()
print(rf_model._estimator_type)

# 학습
rf_model.fit(X_train, y_train)

# 예측
rf_y_pred = rf_model.predict(X_test)
rf_y_pred

classifier


array([2, 0, 2, 1, 1, 1, 2, 0, 1, 1, 0, 0, 2, 1, 2, 1, 1, 0, 0, 1, 2, 1,
       0, 0, 2, 1, 2, 1, 0, 2, 1, 1, 0, 1, 0, 0])

In [69]:
# SVM 사용
from sklearn import svm

svm_model = svm.SVC()
print(svm_model._estimator_type)

# 학습
svm_model.fit(X_train, y_train)

# 예측
svm_y_pred = svm_model.predict(X_test)
svm_y_pred

classifier


array([2, 0, 1, 1, 2, 1, 1, 0, 2, 1, 0, 0, 1, 1, 2, 2, 1, 0, 0, 2, 2, 1,
       0, 0, 2, 1, 1, 1, 0, 2, 1, 1, 0, 1, 0, 0])

In [70]:
# SGDClassifier 사용
from sklearn.linear_model import SGDClassifier

SGDC_model = SGDClassifier()
print(SGDC_model._estimator_type)

# 학습
SGDC_model.fit(X_train, y_train)

# 예측
SGDC_y_pred = SGDC_model.predict(X_test)
SGDC_y_pred

classifier


array([0, 0, 1, 2, 0, 2, 2, 0, 0, 1, 0, 0, 2, 2, 0, 2, 1, 0, 0, 0, 2, 1,
       0, 0, 0, 2, 1, 1, 0, 2, 1, 1, 0, 1, 0, 0])

In [71]:
# Logistic Regression 사용
from sklearn.linear_model import LogisticRegression

lr_model = LogisticRegression()
print(lr_model._estimator_type)

# 학습
lr_model.fit(X_train, y_train)

# 예측
lr_y_pred = lr_model.predict(X_test)
lr_y_pred

classifier


/opt/conda/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


array([2, 0, 2, 1, 1, 1, 2, 0, 1, 1, 0, 0, 2, 1, 2, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 2, 1, 2, 1, 0, 2, 1, 1, 0, 1, 0, 0])

#### (6) 모델을 평가해 보기

In [72]:
# 우선 데이터 불균형을 파악하기 위해 y_train, y_test 값을 봐보자면

import numpy as np
print('y_train')
print(np.unique(y_train, return_counts=True))
print("=======================")
print('y_test')
print(np.unique(y_test, return_counts=True))

# 골고루 섞여있음

y_train
(array([0, 1, 2]), array([47, 56, 39]))
y_test
(array([0, 1, 2]), array([12, 15,  9]))


#### 결론
- 선택한 평가지표 : accuracy
- 이유(1) : 데이터가 골고루 되어 있기에 데이터 전체 갯수에 대한 예측률을 알려주는 accuracy도 모델의 성능을 잘 보여줄 수 있다고 생각
- 이유(2) : 그리고 와인 종류 예측이기에 precision, recall이 critical하게 영향을 주는 것 같지는 않다고 생각했다. 

In [73]:
# 모델별 평가하기
from sklearn.metrics import accuracy_score

print("Decision Tree")
print('Accuracy :', accuracy_score(y_test, dt_y_pred))
print("==================================================")
print("Random Forest")
print('Accuracy :', accuracy_score(y_test, rf_y_pred))
print("==================================================")
print("SVM")
print('Accuracy :', accuracy_score(y_test, svm_y_pred))
print("==================================================")
print("SGD Classifier")
print('Accuracy :', accuracy_score(y_test, SGDC_y_pred))
print("==================================================")
print("Logistic Regression")
print('Accuracy :', accuracy_score(y_test, lr_y_pred))
print("==================================================")

Decision Tree
Accuracy : 0.8611111111111112
Random Forest
Accuracy : 1.0
SVM
Accuracy : 0.7777777777777778
SGD Classifier
Accuracy : 0.6388888888888888
Logistic Regression
Accuracy : 0.9722222222222222


## 2-13. 프로젝트 (3) load_breast_cancer : 유방암 여부를 진단해 봅시다


#### (1) 필요한 모듈 import하기


In [75]:
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

#### (2) 데이터 준비


In [79]:
breast_cancer = load_breast_cancer()


In [81]:
breast_cancer.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])

#### (3) 데이터 이해하기


In [82]:
# 데이터만 따로 저장
bc_data = breast_cancer.data

# 라벨만 따로 저장
bc_label = breast_cancer.target

In [83]:
breast_cancer.feature_names

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23')

In [84]:
breast_cancer.data.shape

(569, 30)

In [86]:
breast_cancer.target_names

# malignant는 악성
# benign은 양성(순함)

array(['malignant', 'benign'], dtype='<U9')

In [90]:
np.unique(bc_label, return_counts=True)

(array([0, 1]), array([212, 357]))

In [91]:
print(breast_cancer.DESCR)

.. _breast_cancer_dataset:

Breast cancer wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 569

    :Number of Attributes: 30 numeric, predictive attributes and the class

    :Attribute Information:
        - radius (mean of distances from center to points on the perimeter)
        - texture (standard deviation of gray-scale values)
        - perimeter
        - area
        - smoothness (local variation in radius lengths)
        - compactness (perimeter^2 / area - 1.0)
        - concavity (severity of concave portions of the contour)
        - concave points (number of concave portions of the contour)
        - symmetry
        - fractal dimension ("coastline approximation" - 1)

        The mean, standard error, and "worst" or largest (mean of the three
        worst/largest values) of these features were computed for each image,
        resulting in 30 features.  For instance, field 0 is Mean Radi

In [93]:
# 데이터를 보면
# 1) breast cancer 의 양성, 악성 여부에 대한 데이터이고
# 2) 이 데이터들의 양성/악성 여부 값은 target에 1차원 벡터(0과 1)로 저장되어 있다.
# 3) 데이터 개수는 569개, 이들의 feature는 30개이다.
# 4) feature는 모두 numeric이다.


#### (4) train, test 데이터 분리


In [94]:
# 데이터셋 분리
X_train, X_test, y_train, y_test = train_test_split(bc_data,
                                                   bc_label,
                                                   test_size=0.2,
                                                   random_state=13)

print(f"X_train 개수는 {len(X_train)}")
print(f"y_train 개수는 {len(y_train)}")
print(f"X_test 개수는 {len(X_test)}")
print(f"y_test 개수는 {len(y_test)}")

X_train 개수는 455
y_train 개수는 455
X_test 개수는 114
y_test 개수는 114


#### (5) 다양한 모델로 학습시켜보기


In [95]:
# Decision Tree 사용
from sklearn.tree import DecisionTreeClassifier
dt_model = DecisionTreeClassifier()
print(dt_model._estimator_type)

# 학습
dt_model.fit(X_train, y_train)

# 예측
dt_y_pred = dt_model.predict(X_test)
dt_y_pred

classifier


array([1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 0, 0, 1])

In [96]:
# Random Forest 사용
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier()
print(rf_model._estimator_type)

# 학습
rf_model.fit(X_train, y_train)

# 예측
rf_y_pred = rf_model.predict(X_test)
rf_y_pred

classifier


array([0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 0, 0, 1])

In [97]:
# SVM 사용
from sklearn import svm

svm_model = svm.SVC()
print(svm_model._estimator_type)

# 학습
svm_model.fit(X_train, y_train)

# 예측
svm_y_pred = svm_model.predict(X_test)
svm_y_pred

classifier


array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 0, 1, 1])

In [98]:
# SGDClassifier 사용
from sklearn.linear_model import SGDClassifier

SGDC_model = SGDClassifier()
print(SGDC_model._estimator_type)

# 학습
SGDC_model.fit(X_train, y_train)

# 예측
SGDC_y_pred = SGDC_model.predict(X_test)
SGDC_y_pred

classifier


array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 0, 1, 1])

In [99]:
# Logistic Regression 사용
from sklearn.linear_model import LogisticRegression

lr_model = LogisticRegression()
print(lr_model._estimator_type)

# 학습
lr_model.fit(X_train, y_train)

# 예측
lr_y_pred = lr_model.predict(X_test)
lr_y_pred

classifier


/opt/conda/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


array([1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 0, 0, 1])

#### (6) 모델을 평가해 보기


In [103]:
# 우선 데이터 불균형을 파악하기 위해 y_train, y_test 값을 봐보자면

import numpy as np
print('y_train')
print(np.unique(y_train, return_counts=True))
print("=======================")
print('y_test')
print(np.unique(y_test, return_counts=True))
print("=======================")

# 비율
y_train_0 = np.unique(y_train, return_counts=True)[1][0]
y_train_1 = np.unique(y_train, return_counts=True)[1][1]
print("y_train 악성 vs 양성 비율은", y_train_0 / (y_train_0 + y_train_1))
y_test_0 = np.unique(y_train, return_counts=True)[1][0]
y_test_1 = np.unique(y_train, return_counts=True)[1][1]
print("y_test 악성 vs 양성 비율은", y_train_0 / (y_test_0 + y_test_1))

# 약 1:2 비율로 악성이 적지만 심한 불균형은 아닌 것으로 판단

y_train
(array([0, 1]), array([176, 279]))
y_test
(array([0, 1]), array([36, 78]))
y_train 악성 vs 양성 비율은 0.3868131868131868
y_test 악성 vs 양성 비율은 0.3868131868131868


#### 결론
- 선택한 평가지표 : recall
- 이유 : 암은 악성(positive)인 것을 놓치는 게(negative로 보는 게) 더 위험하므로 FN이 적어야 하고, 이래서 실제 악성 중 FN이 적은 모델을 판별하는 recall이 좋은 지표인 것 같다.


In [105]:
# 모델별 평가하기

print("Decision Tree")
print(classification_report(y_test, dt_y_pred))
print("==================================================")
print("Random Forest")
print(classification_report(y_test, rf_y_pred))
print("==================================================")
print("SVM")
print(classification_report(y_test, svm_y_pred))
print("==================================================")
print("SGD Classifier")
print(classification_report(y_test, SGDC_y_pred))
print("==================================================")
print("Logistic Regression")
print(classification_report(y_test, lr_y_pred))
print("==================================================")

Decision Tree
              precision    recall  f1-score   support

           0       0.75      0.92      0.83        36
           1       0.96      0.86      0.91        78

    accuracy                           0.88       114
   macro avg       0.85      0.89      0.87       114
weighted avg       0.89      0.88      0.88       114

Random Forest
              precision    recall  f1-score   support

           0       0.81      0.97      0.89        36
           1       0.99      0.90      0.94        78

    accuracy                           0.92       114
   macro avg       0.90      0.93      0.91       114
weighted avg       0.93      0.92      0.92       114

SVM
              precision    recall  f1-score   support

           0       0.84      0.75      0.79        36
           1       0.89      0.94      0.91        78

    accuracy                           0.88       114
   macro avg       0.87      0.84      0.85       114
weighted avg       0.88      0.88      0.8

#### 결론 2
- malignant(0값)의 recall이 가장 좋은 Random Forest를 좋은 모델이라고 선택했다.